### ISSUE TITLE
Missing SQL Injection Techniques

### ISSUE THREAD

**Issue by SebastianOpiyo** [a3cipher/CEH#44]
SQL Injection techniques section is empty.

**Comment by a3cipher** [comment]
Hi @SebastianOpiyo,

1 Can you be more specific which section of which module you would like to see expanded on?
2 If you feel the notes are incomplete / would love to see expanded in some ways, consider contributing as well 😄

**Comment by SebastianOpiyo** [comment]
Hi,

I was actually planning on filling the gaps and will definitely do that.
Thanks.

**Comment by SebastianOpiyo** [comment]
Just to clarify, Module 15, Section 2 to be specific.

Thanks.

**Comment by SebastianOpiyo** [comment]
Made the changes and created PR.
